services:
  dev:
    image: openjdk:17
    links:
      - postgres
      - redis
      - rabbitmq
    command: echo 'dev environment started'
  rabbitmq:
    image: rabbitmq:3-management-alpine  # 官方 RabbitMQ 镜像
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest     # 设置默认用户名
      RABBITMQ_DEFAULT_PASS: guest # 设置默认密码
    ports:
      - "5672:5672"   # AMQP 协议端口
      - "15672:15672" # 管理控制台端口
  redis:
    image: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: plm
      POSTGRES_PASSWORD: plm123456
      POSTGRES_DB: plm_dev
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data