server:
  port: 9099

## database ##
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/permission
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl