server:
  port: 9099

## database ##
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/permission
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

## mybatis ##
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.pyr.permission.model
