server:
  port: 9099

## database ##
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/permission?characterEncoding=UTF-8
    username: root
    password: 19980617pyr
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration

## mybatis ##
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.pyr.permission.model
