server:
  port: 9099

## database ##
spring:
  datasource:
    url: jdbc:sqlserver://39.98.221.38;database=INFlowsDB?currentSchema=INFlowsDB
    username: sa
    password: Mmf@123$%^&
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl